version: 2

before:
  hooks:
    - go mod download
builds:
  - id: kanban-md
    main: ./cmd/kanban-md
    binary: kanban-md
    ldflags:
      - -s -w -X github.com/thegapcloser/kanban-md/cmd.version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
archives:
  - id: default
    builds:
      - kanban-md
    name_template: "kanban-md_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats:
          - zip
release:
  github:
  name_template: "{{.Version}}"
  prerelease: auto
  mode: append
changelog:
  disable: true
